import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "NewYork Times Best Sellers",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="header">
					<Link href="/">
						<span className="menu">Home</span>
					</Link>
					<Link href="/about">
						<span className="menu">About</span>
					</Link>
				</div>
				{children}
			</body>
		</html>
	);
}
